# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
# permalink:        pretty
# relative_permalinks: true

# Setup
title:            Green Park
tagline:          'A Jekyll theme'
description:      '안녕하세요.<br/> 5년차 서버개발자 Green입니다.'
url:              https://green-park-dev.github.io
baseurl:          /

author:
version:          2.1.0

github:
  repo:           https://github.com/green-park-dev
